PATCH   http://localhost:3000/login
Content-Type: application/json

{
  "access": {
    "US_ID":1,
    "US_ACCOUNT":"taigavn113",
    "US_PASSWORD":"123456",
    "TOKEN":null
},
  "US_NEWPASS": "passchanged"
}

### this is login
GET   http://localhost:3000/login
Content-Type: application/json

{
    "US_ID":3,
    "US_ACCOUNT":"PhamMinhTai123",
    "US_PASSWORD":"123456",
    "TOKEN":null
}

### this is Sign up
POST   http://localhost:3000/login
Content-Type: application/json

{
    "US_ID":1,
    "US_ACCOUNT":"account1",
    "US_PASSWORD":"123456",
    "TOKEN":null
}

### this how to get personal info
GET   http://localhost:3000/info
Content-Type: application/json

{
    "US_ID":3,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
}
### this is form to update personal info
POST   http://localhost:3000/info
Content-Type: application/json

{
"access":{
    "US_ID":3,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
        },
"data":{   
    "US_ID": 3,
    "US_NAME": "Pham Minh Tai",
    "US_MAIL": "pmt@clc.fitus.edu.vn",
    "US_PHONE": "0123456789",
    "US_BIRTH": "11/21/2002",
    "US_GENDER": "0",
    "US_ADDRESS": "HCM city3, Vietnam"
    }
}
### this is how to connect Project
GET   http://localhost:3000/project
Content-Type: application/json

{"PJ_ID":1
,"MEM_ID":1
,"MEM_POS":0}
###this is how to create project
POST http://localhost:3000/project
Content-Type: application/json
//các thuộc tính được cmt bắt buộc phải thay đổi giá trị với mỗi user
//còn lại thì không cần điền
//PJ_ID,PJ_CREATEDAY,PJ_ADMIN sẽ được tự động cập nhật

{
  "access": {
    "US_ID":1,
    "US_ACCOUNT":"PhamMinhTai123",
    "US_PASSWORD":"123456",
    "TOKEN":null
},
  "data":{
      "PJ_ID": 0,
      "PJ_NAME": "Software Engineer 3",
      "PJ_CREATEDAY": "2022-08-05T14:03:50.911Z",
      "PJ_DEADLINE": "09/09/2022",
      "PJ_STATUS": "0",
      "PJ_ADMIN": 1,
      "PJ_OWNER": "Khoa CNTT"
  }
}
### update project info
PATCH http://localhost:3000/project
Content-Type: application/json
//các thuộc tính được cmt bắt buộc phải thay đổi giá trị với mỗi user
//còn lại thì không cần điền
//PJ_ID,PJ_CREATEDAY,PJ_ADMIN sẽ được tự động cập nhật

{
  "access": {
     "PJ_ID":1
    ,"MEM_ID":1
    ,"MEM_POS":0
  },
  "data":{
      "PJ_ID": 0,
      "PJ_NAME": "Project 3",
      "PJ_CREATEDAY": "2022-08-05T14:03:50.911Z",
      "PJ_DEADLINE": "09/09/2022",
      "PJ_STATUS": "0",
      "PJ_ADMIN": 1,
      "PJ_OWNER": "SIMPLE"
  }
}
### add member to project
POST  http://localhost:3000/member
Content-Type: application/json

{
  "access": {
     "PJ_ID":1
    ,"MEM_ID":1
    ,"MEM_POS":0
  },
  "data":{
    "US_ID": 2,
    "US_NAME": "Pham Minh Tai",
    "US_MAIL": "pmt@clc.fitus.edu.vn",
    "US_PHONE": "0123456789",
    "US_BIRTH": "11/21/2002",
    "US_GENDER": "0",
    "US_ADDRESS": "HCM city3, Vietnam"
  }
}
### delete a member
DELETE   http://localhost:3000/member
Content-Type: application/json

{
  "access": {
     "PJ_ID":1
    ,"MEM_ID":1
    ,"MEM_POS":0
  },
  "data":{
     "PJ_ID":1
    ,"MEM_ID":2
    ,"MEM_POS":0
  }
}