PATCH   http://localhost:3000/login
Content-Type: application/json

{
  "access": {
    "US_ID":1,
    "US_ACCOUNT":"taigavn113",
    "US_PASSWORD":"123456",
    "TOKEN":null
},
  "US_NEWPASS": "passchanged"
}

### this is login
GET   http://localhost:3000/login
Content-Type: application/json

{
    "US_ID":3,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
}

### this is Sign up
POST   http://localhost:3000/login
Content-Type: application/json

{
    "US_ID":1,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
}

### this how to get personal info
GET   http://localhost:3000/info
Content-Type: application/json

{
    "US_ID":3,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
}
### this is form to update personal info
POST   http://localhost:3000/info
Content-Type: application/json

{
"access":{
    "US_ID":2,
    "US_ACCOUNT":"PhamMinhTai1",
    "US_PASSWORD":"123456",
    "TOKEN":null
        },
"data":{   
    "US_ID": 3,
    "US_NAME": "Pham Minh Tai3",
    "US_MAIL": "pmt@clc.fitus.edu.vn",
    "US_PHONE": "0123456789",
    "US_BIRTH": "11/21/2002",
    "US_GENDER": "0",
    "US_ADDRESS": "HCM city3, Vietnam"
    }
}