-- CreateTable
CREATE TABLE "USER_ACCOUNT" (
    "US_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    "US_ACCOUNT" TEXT NOT NULL,
    "US_PASSWORD" TEXT NOT NULL,
    "TOKEN" TEXT
);

-- CreateTable
CREATE TABLE "USER_INFO" (
    "US_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    "US_NAME" TEXT,
    "US_MAIL" TEXT,
    "US_PHONE" TEXT,
    "US_BIRTH" DATETIME,
    "US_GENDER" TEXT,
    "US_ADDRESS" TEXT,
    CONSTRAINT "USER_INFO_US_ID_fkey" FOREIGN KEY ("US_ID") REFERENCES "USER_ACCOUNT" ("US_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PROJECT_ACCESSIBILITY" (
    "MEM_POS" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DEL_PJ" TEXT,
    "EDIT_MEM_POS" TEXT,
    "EDIT_MEM" TEXT,
    "EDIT_STATUS" TEXT,
    "CREATE_ANNOUNCÊMNT" TEXT
);

-- CreateTable
CREATE TABLE "PROJECT_INFO" (
    "PJ_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PJ_NAME" TEXT,
    "PJ_CREATEDAY" DATETIME,
    "PJ_DEADLINE" DATETIME,
    "PJ_STATUS" TEXT,
    "PJ_ADMIN" INTEGER,
    "PJ_OWNER" TEXT,
    CONSTRAINT "PROJECT_INFO_PJ_ID_PJ_ADMIN_fkey" FOREIGN KEY ("PJ_ID", "PJ_ADMIN") REFERENCES "PROJECT_MEMBER" ("PJ_ID", "MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PROJECT_MEMBER" (
    "PJ_ID" INTEGER NOT NULL,
    "MEM_ID" INTEGER NOT NULL,
    "MEM_POS" INTEGER,

    PRIMARY KEY ("PJ_ID", "MEM_ID"),
    CONSTRAINT "PROJECT_MEMBER_MEM_ID_fkey" FOREIGN KEY ("MEM_ID") REFERENCES "USER_INFO" ("US_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PROJECT_MEMBER_MEM_POS_fkey" FOREIGN KEY ("MEM_POS") REFERENCES "PROJECT_ACCESSIBILITY" ("MEM_POS") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PROJECT_MEMBER_MEM_POS_fkey" FOREIGN KEY ("MEM_POS") REFERENCES "TASK_ACCESSIBILITY" ("MEM_POS") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PROJECT_MEMBER_PJ_ID_fkey" FOREIGN KEY ("PJ_ID") REFERENCES "PROJECT_INFO" ("PJ_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TASK_ACCESSIBILITY" (
    "MEM_POS" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EDIT_MEM" TEXT,
    "ADD_TASK" TEXT,
    "DEL_TASK" TEXT,
    "EDIT_NAME" TEXT,
    "EDIT_DEADLINE" TEXT,
    "EDIT_STATUS" TEXT,
    "EDIT_DESCRIPTION" TEXT
);

-- CreateTable
CREATE TABLE "TASK_INFO" (
    "PJ_ID" INTEGER NOT NULL,
    "TASK_ID" INTEGER NOT NULL,
    "TASK_STATUS" TEXT,
    "TASK_NAME" TEXT,
    "TASK_DESCRIPTON" TEXT,
    "TASK_CREATEDAY" DATETIME,
    "TASK_DEADLINE" DATETIME,
    "TASK_CREATOR" INTEGER,

    PRIMARY KEY ("PJ_ID", "TASK_ID"),
    CONSTRAINT "TASK_INFO_PJ_ID_fkey" FOREIGN KEY ("PJ_ID") REFERENCES "PROJECT_INFO" ("PJ_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TASK_INFO_PJ_ID_TASK_CREATOR_fkey" FOREIGN KEY ("PJ_ID", "TASK_CREATOR") REFERENCES "PROJECT_MEMBER" ("PJ_ID", "MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TASK_RESPONDSIPLE" (
    "PJ_ID" INTEGER NOT NULL,
    "TASK_ID" INTEGER NOT NULL,
    "MEM_ID" INTEGER NOT NULL,

    PRIMARY KEY ("PJ_ID", "TASK_ID", "MEM_ID"),
    CONSTRAINT "TASK_RESPONDSIPLE_PJ_ID_MEM_ID_fkey" FOREIGN KEY ("PJ_ID", "MEM_ID") REFERENCES "PROJECT_MEMBER" ("PJ_ID", "MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TASK_RESPONDSIPLE_PJ_ID_TASK_ID_fkey" FOREIGN KEY ("PJ_ID", "TASK_ID") REFERENCES "TASK_INFO" ("PJ_ID", "TASK_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
